// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using game_server.Context;

namespace game_server.Migrations
{
    [DbContext(typeof(GameSessionModelDbContext))]
    [Migration("20191215215647_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("game_server.Database.Models.GameInfo", b =>
                {
                    b.Property<Guid>("GameInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GameInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GameName")
                        .HasColumnName("GameName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameInfoId");

                    b.ToTable("GameInfo","Games");

                    b.HasData(
                        new
                        {
                            GameInfoId = new Guid("c2ebe68a-6059-4351-8443-4491bc3bab48"),
                            GameName = "Escoba"
                        },
                        new
                        {
                            GameInfoId = new Guid("31616261-d554-4c90-9e8d-03bd49d8f56f"),
                            GameName = "Pusoy Dos"
                        });
                });

            modelBuilder.Entity("game_server.Database.Models.GameSession", b =>
                {
                    b.Property<Guid>("GameSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GameSessionState")
                        .HasColumnName("GameSessionState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameStates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameStatisticId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameSessionId");

                    b.HasIndex("GameInfoId");

                    b.HasIndex("GameStatisticId");

                    b.ToTable("GameSessions","Games");
                });

            modelBuilder.Entity("game_server.Database.Models.GameStatistic", b =>
                {
                    b.Property<Guid>("GameStatisticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GameStatisticId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AiWin")
                        .HasColumnName("AiWin")
                        .HasColumnType("bit");

                    b.Property<bool?>("Draw")
                        .HasColumnName("Draw")
                        .HasColumnType("bit");

                    b.Property<string>("FinalScore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GameComplete")
                        .HasColumnName("GameComplete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GameEnd")
                        .HasColumnName("GameEnd")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GameStart")
                        .HasColumnName("GameStart")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("HumanWin")
                        .HasColumnName("HumanWin")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserStatisticId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameStatisticId");

                    b.HasIndex("GameInfoId");

                    b.HasIndex("GameSessionId")
                        .IsUnique();

                    b.HasIndex("UserStatisticId");

                    b.ToTable("GameStatistics","Games");
                });

            modelBuilder.Entity("game_server.Database.Models.Rule", b =>
                {
                    b.Property<Guid>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RuleName")
                        .HasColumnName("RuleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleText")
                        .HasColumnName("RuleText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RuleId");

                    b.HasIndex("GameInfoId");

                    b.HasIndex("UserId");

                    b.ToTable("Rules","Games");
                });

            modelBuilder.Entity("game_server.Database.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .HasColumnName("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnName("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnName("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users","Games");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("3e74ec77-32a3-4a1e-ade6-9ab9afc9d37f"),
                            EmailAddress = "jdoe@acme.com",
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            UserId = new Guid("bd4953f8-6a6c-455c-8078-e8d07596008b"),
                            EmailAddress = "ai@escoba.com",
                            FirstName = "Hal",
                            LastName = "9000"
                        });
                });

            modelBuilder.Entity("game_server.Database.Models.UserGameSession", b =>
                {
                    b.Property<Guid>("UserGameSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserGameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GameStatisticId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserGameSessionId");

                    b.HasIndex("GameInfoId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("GameStatisticId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGameSessions","Games");
                });

            modelBuilder.Entity("game_server.Database.Models.UserStatistic", b =>
                {
                    b.Property<Guid>("UserStatisticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserStatisticId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Draws")
                        .HasColumnName("Draws")
                        .HasColumnType("int");

                    b.Property<Guid>("GameInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Losses")
                        .HasColumnName("Losses")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPlays")
                        .HasColumnName("NumberOfPlays")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Wins")
                        .HasColumnName("Wins")
                        .HasColumnType("int");

                    b.HasKey("UserStatisticId");

                    b.HasIndex("GameInfoId");

                    b.HasIndex("UserId");

                    b.ToTable("UserStatistics","Games");

                    b.HasData(
                        new
                        {
                            UserStatisticId = new Guid("e03841ba-0c15-4844-82f3-3563b441a352"),
                            Draws = 0,
                            GameInfoId = new Guid("c2ebe68a-6059-4351-8443-4491bc3bab48"),
                            Losses = 0,
                            NumberOfPlays = 0,
                            UserId = new Guid("3e74ec77-32a3-4a1e-ade6-9ab9afc9d37f"),
                            Wins = 0
                        },
                        new
                        {
                            UserStatisticId = new Guid("fb08cb85-86c2-4beb-bd29-11c010befb5a"),
                            Draws = 0,
                            GameInfoId = new Guid("c2ebe68a-6059-4351-8443-4491bc3bab48"),
                            Losses = 0,
                            NumberOfPlays = 0,
                            UserId = new Guid("bd4953f8-6a6c-455c-8078-e8d07596008b"),
                            Wins = 0
                        });
                });

            modelBuilder.Entity("game_server.Database.Models.GameSession", b =>
                {
                    b.HasOne("game_server.Database.Models.GameInfo", "GameInfo")
                        .WithMany("GameSessions")
                        .HasForeignKey("GameInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("game_server.Database.Models.GameStatistic", b =>
                {
                    b.HasOne("game_server.Database.Models.GameInfo", "GameInfo")
                        .WithMany("GameStatistics")
                        .HasForeignKey("GameInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("game_server.Database.Models.GameSession", "GameSession")
                        .WithOne("GameStatistic")
                        .HasForeignKey("game_server.Database.Models.GameStatistic", "GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("game_server.Database.Models.UserStatistic", "UserStatistic")
                        .WithMany("GameStatistics")
                        .HasForeignKey("UserStatisticId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("game_server.Database.Models.Rule", b =>
                {
                    b.HasOne("game_server.Database.Models.GameInfo", "GameInfo")
                        .WithMany("Rules")
                        .HasForeignKey("GameInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("game_server.Database.Models.User", "User")
                        .WithMany("Rules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("game_server.Database.Models.UserGameSession", b =>
                {
                    b.HasOne("game_server.Database.Models.GameInfo", "GameInfo")
                        .WithMany("UserGameSessions")
                        .HasForeignKey("GameInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("game_server.Database.Models.GameSession", "GameSession")
                        .WithMany("UserGameSessions")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("game_server.Database.Models.GameStatistic", "GameStatistic")
                        .WithMany()
                        .HasForeignKey("GameStatisticId");

                    b.HasOne("game_server.Database.Models.User", "User")
                        .WithMany("UserGameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("game_server.Database.Models.UserStatistic", b =>
                {
                    b.HasOne("game_server.Database.Models.GameInfo", "GameInfo")
                        .WithMany("UserStatistics")
                        .HasForeignKey("GameInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("game_server.Database.Models.User", "User")
                        .WithMany("UserStatistics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
