export const types = {
  SET_CLIENT_SESSION_ID: 'SET_CLIENT_SESSION_ID',
  CHANGE_GAME_DATA_ERRORED: 'CHANGE_GAME_DATA_ERRORED',
  CHANGE_GAME_DATA_LOADED: 'CHANGE_GAME_DATA_LOADED',
  INIT_GAME_DATA: 'INIT_GAME_DATA',
  CHANGE_GAME_DATA: 'CHANGE_GAME_DATA',
  CHANGE_VALID_PLAYS_ERRORED: 'CHANGE_VALID_PLAYS_ERRORED',
  CHANGE_VALID_PLAYS_LOADED: 'CHANGE_VALID_PLAYS_LOADED',
  CHANGE_VALID_PLAYS: 'CHANGE_VALID_PLAYS',
  CHANGE_PLAYER_1_DATA: 'CHANGE_PLAYER_1_DATA',
  CHANGE_PLAYER_2_DATA: 'CHANGE_PLAYER_2_DATA',
  CHANGE_TABLE_CARD_DATA: 'CHANGE_TABLE_CARD_DATA',
  LOAD_RULE_DATA: 'LOAD_RULE_DATA',
  CHANGE_RULE_DATA_ERRORED: 'CHANGE_RULE_DATA_ERRORED',
  CHANGE_RULE_DATA_LOADED: 'CHANGE_RULE_DATA_LOADED'
}
